### PR TITLE
Icon only mode + making Blue icon less noticeable

### PR DESCRIPTION
**Pull request by martin-bloksa**
I changed the code of script.js to:

- Remove the text and border next to the badges
- Make both badges approx. the same size
- Reduce the visual importance of Blue badge and make it less noticeable than the Verified badge

### CODE REVIEW

**Comment by martin-bloksa** [comment]
Tested on 2 Windows computers, Chrome, Dark mode only.

**Comment by CJStyles123** [comment]
I love this, is there any way to have this affect the notifications tab too?

**Comment by martin-bloksa** [comment]
> I love this, is there any way to have this affect the notifications tab too?

I only did the "reskin", it seems like the extension code itself doesn't work in the "Verified" notifications tab. So that would be a question for @wseagar

**Comment by wseagar** [comment]
Hey thanks for this but we're going to make these options configurable. Can you have a look at master I've put in the plumbing for an options panel and have added my own version of disabling the text. Feel free to work this change into the new options system if you can find a place!

**Comment by wseagar** [comment]
These changes have been included with the options panel and the PR is now out of date. Thanks for contributing though!

**Pull request closed without merging**
